apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-jenkins
spec:
  storageClassName: pv-pvc-link
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/home/mikael/volumes/helm-jenkins" #host location

