apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-13T07:18:30Z"
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: helm-jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.7.6
  name: helm-jenkins
  namespace: default
  resourceVersion: "10932"
  selfLink: /api/v1/namespaces/default/services/helm-jenkins
  uid: 0121f09a-31a5-4643-bb05-a99fa2f56532
spec:
  clusterIP: 10.104.23.23
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: helm-jenkins
  sessionAffinity: None
  type: NodePort
